/*
 * errorcode.h
 *
 *  Created on: 2016/02/25
 *      Author: toshio
 */

#ifndef DATAMANAGE_ERRORCODE_H_
#define DATAMANAGE_ERRORCODE_H_


#define	_ERRORCODE_NOTHING				0x00
#define	_ERRORCODE_WATER_EMPTY			0x01
#define	_ERRORCODE_WATERPRESSURE_SENSOR	0x02
#define	_ERRORCODE_WATERLEVEL_SENSOR	0x04
#define	_ERRORCODE_TEMPERATURE_SENSOR	0x08
#define	_ERRORCODE_TEMPERATURE			0x10
#define	_ERRORCODE_COMMUNIACTIN			0x20
#define	_ERRORCODE_CONTACTOR			0x40
#define	_ERRORCODE_SYSTEM				0x80

#endif /* DATAMANAGE_ERRORCODE_H_ */
